const express = require('express');
const puppeteer = require('puppeteer');
const bodyParser = require('body-parser');
const app = express();

app.use(bodyParser.json());

app.post("/generate", async (req, res) => {
  const { customer, selections } = req.body;

  // Log incoming data for debugging
  console.log('Received data:', req.body);

  if (!customer || !selections) {
    res.status(400).send("Missing required data");
    return;
  }

  try {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    // Define your HTML template here
    const htmlContent = `
    <html>
      <body>
        <div style="font-family: 'Inter', sans-serif; max-width: 880px; margin: 0 auto; padding: 24px;">
          <h1 style="color: #DAA520;">Unit Selection Summary</h1>
          
          <h2 style="color: #DAA520; font-weight: 600;">Purchaser Details</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr><td><strong>Full Name:</strong></td><td>${customer.firstName} ${customer.lastName}</td></tr>
            <tr><td><strong>ID Number:</strong></td><td>${customer.idNumber}</td></tr>
            <tr><td><strong>Email:</strong></td><td>${customer.email}</td></tr>
            <tr><td><strong>Phone:</strong></td><td>${customer.phone}</td></tr>
          </table>

          <h2 style="color: #DAA520; font-weight: 600;">Moodboard Selections</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr><td><strong>Kitchen:</strong></td><td>${selections.kitchen.name} - R${selections.kitchen.price}</td></tr>
            <tr><td><strong>Bathroom:</strong></td><td>${selections.bathroom.name} - R${selections.bathroom.price}</td></tr>
          </table>

          <h2 style="color: #DAA520; font-weight: 600;">Upgrades</h2>
          <ul>
            ${selections.upgrades.map(upgrade => `
              <li><strong>${upgrade.category}</strong> ${upgrade.name} – R${upgrade.price}</li>
            `).join('')}
          </ul>

          <h3 style="font-weight: 700;">Total Investment: R${selections.totalInvestment}</h3>

          <footer style="font-size: 11px; color: #6b7280; text-align: center; margin-top: 32px; padding-top: 12px;">
            Generated by 27 Grey Configurator | For summary purposes only – not a tax invoice.
          </footer>
        </div>
      </body>
    </html>
    `;

    await page.setContent(htmlContent);
    const pdfBuffer = await page.pdf({ format: 'A4' });

    await browser.close();

    res.contentType('application/pdf');
    res.send(pdfBuffer);
  } catch (error) {
    console.error("Error generating PDF:", error);
    res.status(500).send("Error generating PDF");
  }
});

app.listen(3000, () => {
  console.log("Server is running on http://localhost:3000");
});
